"""password_to_user

Revision ID: 570411f1c747
Revises: 078043ac530f
Create Date: 2023-04-08 15:05:18.645422

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "570411f1c747"
down_revision = "078043ac530f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "password",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="123",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###
