"""empty message

Revision ID: 934f3649303a
Revises: ac0c92117e08
Create Date: 2023-04-15 22:46:22.861212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "934f3649303a"
down_revision = "ac0c92117e08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "product_tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product", sa.Integer(), nullable=True),
        sa.Column("tag", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_tag")
    op.drop_table("tag")
    op.drop_table("product")
    # ### end Alembic commands ###
