"""empty message

Revision ID: c3d0fa63c23e
Revises: ac0c92117e08
Create Date: 2023-04-30 21:59:58.363931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3d0fa63c23e"
down_revision = "ac0c92117e08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("url", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("url"),
    )
    op.alter_column(
        "user", "name", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    op.alter_column(
        "user", "password", existing_type=sa.VARCHAR(length=64), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "password", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.alter_column(
        "user", "name", existing_type=sa.VARCHAR(length=64), nullable=True
    )
    op.drop_table("attachment")
    # ### end Alembic commands ###
